version: '3'

services:
  api:
    image: alvinejmc.azurecr.io/alvine28/jmcsampleapp-compose:latest
    container_name: jmcsample-app
    build:
      context: .
    ports:
      - 1338:1338
