apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jmcsample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jmcsample-app
    spec:
      containers:
      - name: jmcsample-app
        image: alvinejmc.azurecr.io/alvine28/jmcsampleapp-compose:latest
        ports:
        - containerPort: 1338
      imagePullSecrets:
      - name: acr-auth
