apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jmcsample-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: jmcsample-app
    spec:
      containers:
      - name: jmcsample-app
        image: alvinejmc.azurecr.io/alvine28/jmcsampleapp-compose:latest
        ports:
        - containerPort: 1338
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: acr-auth
            
apiVersion: v1
kind: Service
metadata:
  name: jmcsample-app
spec:
  type: LoadBalancer
  ports:
  - port: 1338
  selector:
    app: jmcsample-app
