apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmcsample-app
  labels:
    app: jmcsample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jmcsample-app
    spec:
      containers:
      - name: jmcsample-app
        image: alvinejmc.azurecr.io/alvine28/jmcsampleapp-compose:latest
        ports:
        - containerPort: 1338
