apiVersion: extensions/v1beta1
kind: Deployment

version: '3'
services:
  jmcsample-app:
    build: .
    image: alvinejmc.azurecr.io/alvine28/jmcsampleapp-compose:latest
    container_name: jmcsample-app
    ports:
        - "1338:1338"
